# Generated by Django 4.2.4 on 2023-09-27 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppElevator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppElevator.autor'),
        ),
    ]
